"""empty message

Revision ID: 41b918edfffa
Revises: 
Create Date: 2024-05-30 19:48:02.247528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b918edfffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False, comment='管理员id'),
    sa.Column('username', sa.String(length=30), nullable=False, comment='用户名'),
    sa.Column('account', sa.String(length=20), nullable=False, comment='账号'),
    sa.Column('password', sa.String(length=200), nullable=False, comment='密码（密文）'),
    sa.Column('email', sa.String(length=30), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='电话'),
    sa.Column('sex', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('intro', sa.String(length=500), nullable=True, comment='介绍'),
    sa.Column('code', sa.String(length=200), nullable=False, comment='邀请码'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('username')
    )
    op.create_table('code',
    sa.Column('invite_code', sa.String(length=100), nullable=False, comment='邀请码'),
    sa.PrimaryKeyConstraint('invite_code')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='真实姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False, comment='活动id'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('situation_province', sa.String(length=100), nullable=False, comment='地点 -- 省份'),
    sa.Column('situation_city', sa.String(length=100), nullable=False, comment='地点 -- 县级市'),
    sa.Column('require_num', sa.Integer(), nullable=False, comment='活动所需人数'),
    sa.Column('value', sa.Integer(), nullable=False, comment='可获得的志愿时长'),
    sa.Column('is_start', sa.Boolean(), nullable=True, comment='是否已经发布'),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('start_time', 'end_time', 'situation_province', 'situation_city'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user_project',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_project')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('code')
    op.drop_table('admin')
    # ### end Alembic commands ###
