"""empty message

Revision ID: e4f49405f1b3
Revises: 41b918edfffa
Create Date: 2024-06-03 17:21:30.530728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f49405f1b3'
down_revision = '41b918edfffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judge', sa.Boolean(), nullable=True, comment='是否审核'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('judge')

    # ### end Alembic commands ###
